package com.mcculloch.pokemon.Templates;

public class TemplateItem {
    final public String name, description;
    final public int bag;

    public TemplateItem(String name, String description, int bag){
        this.name = name;
        this.description = description;
        this.bag = bag;
    }

//    bag key
//    0 = unknown
//    1 = items
//    2 = medicine
//    3 = berries
//    4 = tms
//    5 = power stones
//    6 = key items

//to get id: line # minus 25

    public static TemplateItem[] itemList = {
            new TemplateItem("Placeholder","It holds your place", 0),
            new TemplateItem("Master Ball","Description",1),
            new TemplateItem("Ultra Ball","Description",1),
            new TemplateItem("Great Ball","Description",1),
            new TemplateItem("Poké Ball","Description",1),
            new TemplateItem("Safari Ball","Description",1),
            new TemplateItem("Net Ball","Description",1),
            new TemplateItem("Dive Ball","Description",1),
            new TemplateItem("Nest Ball","Description",1),
            new TemplateItem("Repeat Ball","Description",1),
            new TemplateItem("Timer Ball","Description",1),
            new TemplateItem("Luxury Ball","Description",1),
            new TemplateItem("Premier Ball","Description",1),
            new TemplateItem("Dusk Ball","Description",1),
            new TemplateItem("Heal Ball","Description",1),
            new TemplateItem("Quick Ball","Description",1),
            new TemplateItem("Cherish Ball","Description",1),
            new TemplateItem("Potion","Description",2),
            new TemplateItem("Antidote","Description",2),
            new TemplateItem("Burn Heal","Description",2),
            new TemplateItem("Ice Heal","Description",2),
            new TemplateItem("Awakening","Description",2),
            new TemplateItem("Paralyze Heal","Description",2),
            new TemplateItem("Full Restore","Description",2),
            new TemplateItem("Max Potion","Description",2),
            new TemplateItem("Hyper Potion","Description",2),
            new TemplateItem("Super Potion","Description",2),
            new TemplateItem("Full Heal","Description",2),
            new TemplateItem("Revive","Description",2),
            new TemplateItem("Max Revive","Description",2),
            new TemplateItem("Fresh Water","Description",2),
            new TemplateItem("Soda Pop","Description",2),
            new TemplateItem("Lemonade","Description",2),
            new TemplateItem("Moomoo Milk","Description",2),
            new TemplateItem("Energy Powder","Description",2),
            new TemplateItem("Energy Root","Description",2),
            new TemplateItem("Heal Powder","Description",2),
            new TemplateItem("Revival Herb","Description",2),
            new TemplateItem("Ether","Description",2),
            new TemplateItem("Max Ether","Description",2),
            new TemplateItem("Elixir","Description",2),
            new TemplateItem("Max Elixir","Description",2),
            new TemplateItem("Lava Cookie","Description",2),
            new TemplateItem("Berry Juice","Description",2),
            new TemplateItem("Sacred Ash","Description",2),
            new TemplateItem("HP Up","Description",2),
            new TemplateItem("Protein","Description",2),
            new TemplateItem("Iron","Description",2),
            new TemplateItem("Carbos","Description",2),
            new TemplateItem("Calcium","Description",2),
            new TemplateItem("Rare Candy","Description",2),
            new TemplateItem("PP Up","Description",2),
            new TemplateItem("Zinc","Description",2),
            new TemplateItem("PP Max","Description",2),
            new TemplateItem("Old Gateau","Description",2),
            new TemplateItem("Guard Spec.","Description",1),
            new TemplateItem("Dire Hit","Description",1),
            new TemplateItem("X Attack","Description",1),
            new TemplateItem("X Defense","Description",1),
            new TemplateItem("X Speed","Description",1),
            new TemplateItem("X Accuracy","Description",1),
            new TemplateItem("X Sp. Atk","Description",1),
            new TemplateItem("X Sp. Def","Description",1),
            new TemplateItem("Poké Doll","Description",1),
            new TemplateItem("Fluffy Tail","Description",1),
            new TemplateItem("Blue Flute","Description",1),
            new TemplateItem("Yellow Flute","Description",1),
            new TemplateItem("Red Flute","Description",1),
            new TemplateItem("Black Flute","Description",1),
            new TemplateItem("White Flute","Description",1),
            new TemplateItem("Shoal Salt","Description",1),
            new TemplateItem("Shoal Shell","Description",1),
            new TemplateItem("Red Shard","Description",1),
            new TemplateItem("Blue Shard","Description",1),
            new TemplateItem("Yellow Shard","Description",1),
            new TemplateItem("Green Shard","Description",1),
            new TemplateItem("Super Repel","Description",1),
            new TemplateItem("Max Repel","Description",1),
            new TemplateItem("Escape Rope","Description",1),
            new TemplateItem("Repel","Description",1),
            new TemplateItem("Sun Stone","Description",1),
            new TemplateItem("Moon Stone","Description",1),
            new TemplateItem("Fire Stone","Description",1),
            new TemplateItem("Thunder Stone","Description",1),
            new TemplateItem("Water Stone","Description",1),
            new TemplateItem("Leaf Stone","Description",1),
            new TemplateItem("Tiny Mushroom","Description",1),
            new TemplateItem("Big Mushroom","Description",1),
            new TemplateItem("Pearl","Description",1),
            new TemplateItem("Big Pearl","Description",1),
            new TemplateItem("Stardust","Description",1),
            new TemplateItem("Star Piece","Description",1),
            new TemplateItem("Nugget","Description",1),
            new TemplateItem("Heart Scale","Description",1),
            new TemplateItem("Honey","Description",1),
            new TemplateItem("Growth Mulch","Description",1),
            new TemplateItem("Damp Mulch","Description",1),
            new TemplateItem("Stable Mulch","Description",1),
            new TemplateItem("Gooey Mulch","Description",1),
            new TemplateItem("Root Fossil","Description",1),
            new TemplateItem("Claw Fossil","Description",1),
            new TemplateItem("Helix Fossil","Description",1),
            new TemplateItem("Dome Fossil","Description",1),
            new TemplateItem("Old Amber","Description",1),
            new TemplateItem("Armor Fossil","Description",1),
            new TemplateItem("Skull Fossil","Description",1),
            new TemplateItem("Rare Bone","Description",1),
            new TemplateItem("Shiny Stone","Description",1),
            new TemplateItem("Dusk Stone","Description",1),
            new TemplateItem("Dawn Stone","Description",1),
            new TemplateItem("Oval Stone","Description",1),
            new TemplateItem("Odd Keystone","Description",1),
            new TemplateItem("Griseous Orb","Description",1),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("Douse Drive","Description",1),
            new TemplateItem("Shock Drive","Description",1),
            new TemplateItem("Burn Drive","Description",1),
            new TemplateItem("Chill Drive","Description",1),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("Sweet Heart","Description",2),
            new TemplateItem("Adamant Orb","Description",1),
            new TemplateItem("Lustrous Orb","Description",1),
            new TemplateItem("Greet Mail","Description",1),
            new TemplateItem("Favored Mail","Description",1),
            new TemplateItem("RSVP Mail","Description",1),
            new TemplateItem("Thanks Mail","Description",1),
            new TemplateItem("Inquiry Mail","Description",1),
            new TemplateItem("Like Mail","Description",1),
            new TemplateItem("Reply Mail","Description",1),
            new TemplateItem("Bridge Mail S","Description",1),
            new TemplateItem("Bridge Mail D","Description",1),
            new TemplateItem("Bridge Mail T","Description",1),
            new TemplateItem("Bridge Mail V","Description",1),
            new TemplateItem("Bridge Mail M","Description",1),
            new TemplateItem("Cheri Berry","Description",3),
            new TemplateItem("Chesto Berry","Description",3),
            new TemplateItem("Pecha Berry","Description",3),
            new TemplateItem("Rawst Berry","Description",3),
            new TemplateItem("Aspear Berry","Description",3),
            new TemplateItem("Leppa Berry","Description",3),
            new TemplateItem("Oran Berry","Description",3),
            new TemplateItem("Persim Berry","Description",3),
            new TemplateItem("Lum Berry","Description",3),
            new TemplateItem("Sitrus Berry","Description",3),
            new TemplateItem("Figy Berry","Description",3),
            new TemplateItem("Wiki Berry","Description",3),
            new TemplateItem("Mago Berry","Description",3),
            new TemplateItem("Aguav Berry","Description",3),
            new TemplateItem("Iapapa Berry","Description",3),
            new TemplateItem("Razz Berry","Description",3),
            new TemplateItem("Bluk Berry","Description",3),
            new TemplateItem("Nanab Berry","Description",3),
            new TemplateItem("Wepear Berry","Description",3),
            new TemplateItem("Pinap Berry","Description",3),
            new TemplateItem("Pomeg Berry","Description",3),
            new TemplateItem("Kelpsy Berry","Description",3),
            new TemplateItem("Qualot Berry","Description",3),
            new TemplateItem("Hondew Berry","Description",3),
            new TemplateItem("Grepa Berry","Description",3),
            new TemplateItem("Tamato Berry","Description",3),
            new TemplateItem("Cornn Berry","Description",3),
            new TemplateItem("Magost Berry","Description",3),
            new TemplateItem("Rabuta Berry","Description",3),
            new TemplateItem("Nomel Berry","Description",3),
            new TemplateItem("Spelon Berry","Description",3),
            new TemplateItem("Pamtre Berry","Description",3),
            new TemplateItem("Watmel Berry","Description",3),
            new TemplateItem("Durin Berry","Description",3),
            new TemplateItem("Belue Berry","Description",3),
            new TemplateItem("Occa Berry","Description",3),
            new TemplateItem("Passho Berry","Description",3),
            new TemplateItem("Wacan Berry","Description",3),
            new TemplateItem("Rindo Berry","Description",3),
            new TemplateItem("Yache Berry","Description",3),
            new TemplateItem("Chople Berry","Description",3),
            new TemplateItem("Kebia Berry","Description",3),
            new TemplateItem("Shuca Berry","Description",3),
            new TemplateItem("Coba Berry","Description",3),
            new TemplateItem("Payapa Berry","Description",3),
            new TemplateItem("Tanga Berry","Description",3),
            new TemplateItem("Charti Berry","Description",3),
            new TemplateItem("Kasib Berry","Description",3),
            new TemplateItem("Haban Berry","Description",3),
            new TemplateItem("Colbur Berry","Description",3),
            new TemplateItem("Babiri Berry","Description",3),
            new TemplateItem("Chilan Berry","Description",3),
            new TemplateItem("Liechi Berry","Description",3),
            new TemplateItem("Ganlon Berry","Description",3),
            new TemplateItem("Salac Berry","Description",3),
            new TemplateItem("Petaya Berry","Description",3),
            new TemplateItem("Apicot Berry","Description",3),
            new TemplateItem("Lansat Berry","Description",3),
            new TemplateItem("Starf Berry","Description",3),
            new TemplateItem("Enigma Berry","Description",3),
            new TemplateItem("Micle Berry","Description",3),
            new TemplateItem("Custap Berry","Description",3),
            new TemplateItem("Jaboca Berry","Description",3),
            new TemplateItem("Rowap Berry","Description",3),
            new TemplateItem("Bright Powder","Description",1),
            new TemplateItem("White Herb","Description",1),
            new TemplateItem("Macho Brace","Description",1),
            new TemplateItem("Exp. Share","Description",6),
            new TemplateItem("Quick Claw","Description",1),
            new TemplateItem("Soothe Bell","Description",1),
            new TemplateItem("Mental Herb","Description",1),
            new TemplateItem("Choice Band","Description",1),
            new TemplateItem("King's Rock","Description",1),
            new TemplateItem("Silver Powder","Description",1),
            new TemplateItem("Amulet Coin","Description",1),
            new TemplateItem("Cleanse Tag","Description",1),
            new TemplateItem("Soul Dew","Description",1),
            new TemplateItem("Deep Sea Tooth","Description",1),
            new TemplateItem("Deep Sea Scale","Description",1),
            new TemplateItem("Smoke Ball","Description",1),
            new TemplateItem("Everstone","Description",1),
            new TemplateItem("Focus Band","Description",1),
            new TemplateItem("Lucky Egg","Description",1),
            new TemplateItem("Scope Lens","Description",1),
            new TemplateItem("Metal Coat","Description",1),
            new TemplateItem("Leftovers","Description",1),
            new TemplateItem("Dragon Scale","Description",1),
            new TemplateItem("Light Ball","Description",1),
            new TemplateItem("Soft Sand","Description",1),
            new TemplateItem("Hard Stone","Description",1),
            new TemplateItem("Miracle Seed","Description",1),
            new TemplateItem("Black Glasses","Description",1),
            new TemplateItem("Black Belt","Description",1),
            new TemplateItem("Magnet","Description",1),
            new TemplateItem("Mystic Water","Description",1),
            new TemplateItem("Sharp Beak","Description",1),
            new TemplateItem("Poison Barb","Description",1),
            new TemplateItem("Never-Melt Ice","Description",1),
            new TemplateItem("Spell Tag","Description",1),
            new TemplateItem("Twisted Spoon","Description",1),
            new TemplateItem("Charcoal","Description",1),
            new TemplateItem("Dragon Fang","Description",1),
            new TemplateItem("Silk Scarf","Description",1),
            new TemplateItem("Up-Grade","Description",1),
            new TemplateItem("Shell Bell","Description",1),
            new TemplateItem("Sea Incense","Description",1),
            new TemplateItem("Lax Incense","Description",1),
            new TemplateItem("Lucky Punch","Description",1),
            new TemplateItem("Metal Powder","Description",1),
            new TemplateItem("Thick Club","Description",1),
            new TemplateItem("Stick","Description",1),
            new TemplateItem("Red Scarf","Description",1),
            new TemplateItem("Blue Scarf","Description",1),
            new TemplateItem("Pink Scarf","Description",1),
            new TemplateItem("Green Scarf","Description",1),
            new TemplateItem("Yellow Scarf","Description",1),
            new TemplateItem("Wide Lens","Description",1),
            new TemplateItem("Muscle Band","Description",1),
            new TemplateItem("Wise Glasses","Description",1),
            new TemplateItem("Expert Belt","Description",1),
            new TemplateItem("Light Clay","Description",1),
            new TemplateItem("Life Orb","Description",1),
            new TemplateItem("Power Herb","Description",1),
            new TemplateItem("Toxic Orb","Description",1),
            new TemplateItem("Flame Orb","Description",1),
            new TemplateItem("Quick Powder","Description",1),
            new TemplateItem("Focus Sash","Description",1),
            new TemplateItem("Zoom Lens","Description",1),
            new TemplateItem("Metronome","Description",1),
            new TemplateItem("Iron Ball","Description",1),
            new TemplateItem("Lagging Tail","Description",1),
            new TemplateItem("Destiny Knot","Description",1),
            new TemplateItem("Black Sludge","Description",1),
            new TemplateItem("Icy Rock","Description",1),
            new TemplateItem("Smooth Rock","Description",1),
            new TemplateItem("Heat Rock","Description",1),
            new TemplateItem("Damp Rock","Description",1),
            new TemplateItem("Grip Claw","Description",1),
            new TemplateItem("Choice Scarf","Description",1),
            new TemplateItem("Sticky Barb","Description",1),
            new TemplateItem("Power Bracer","Description",1),
            new TemplateItem("Power Belt","Description",1),
            new TemplateItem("Power Lens","Description",1),
            new TemplateItem("Power Band","Description",1),
            new TemplateItem("Power Anklet","Description",1),
            new TemplateItem("Power Weight","Description",1),
            new TemplateItem("Shed Shell","Description",1),
            new TemplateItem("Big Root","Description",1),
            new TemplateItem("Choice Specs","Description",1),
            new TemplateItem("Flame Plate","Description",1),
            new TemplateItem("Splash Plate","Description",1),
            new TemplateItem("Zap Plate","Description",1),
            new TemplateItem("Meadow Plate","Description",1),
            new TemplateItem("Icicle Plate","Description",1),
            new TemplateItem("Fist Plate","Description",1),
            new TemplateItem("Toxic Plate","Description",1),
            new TemplateItem("Earth Plate","Description",1),
            new TemplateItem("Sky Plate","Description",1),
            new TemplateItem("Mind Plate","Description",1),
            new TemplateItem("Insect Plate","Description",1),
            new TemplateItem("Stone Plate","Description",1),
            new TemplateItem("Spooky Plate","Description",1),
            new TemplateItem("Draco Plate","Description",1),
            new TemplateItem("Dread Plate","Description",1),
            new TemplateItem("Iron Plate","Description",1),
            new TemplateItem("Odd Incense","Description",1),
            new TemplateItem("Rock Incense","Description",1),
            new TemplateItem("Full Incense","Description",1),
            new TemplateItem("Wave Incense","Description",1),
            new TemplateItem("Rose Incense","Description",1),
            new TemplateItem("Luck Incense","Description",1),
            new TemplateItem("Pure Incense","Description",1),
            new TemplateItem("Protector","Description",1),
            new TemplateItem("Electirizer","Description",1),
            new TemplateItem("Magmarizer","Description",1),
            new TemplateItem("Dubious Disc","Description",1),
            new TemplateItem("Reaper Cloth","Description",1),
            new TemplateItem("Razor Claw","Description",1),
            new TemplateItem("Razor Fang","Description",1),
            new TemplateItem("TM01","Description",4),
            new TemplateItem("TM02","Description",4),
            new TemplateItem("TM03","Description",4),
            new TemplateItem("TM04","Description",4),
            new TemplateItem("TM05","Description",4),
            new TemplateItem("TM06","Description",4),
            new TemplateItem("TM07","Description",4),
            new TemplateItem("TM08","Description",4),
            new TemplateItem("TM09","Description",4),
            new TemplateItem("TM10","Description",4),
            new TemplateItem("TM11","Description",4),
            new TemplateItem("TM12","Description",4),
            new TemplateItem("TM13","Description",4),
            new TemplateItem("TM14","Description",4),
            new TemplateItem("TM15","Description",4),
            new TemplateItem("TM16","Description",4),
            new TemplateItem("TM17","Description",4),
            new TemplateItem("TM18","Description",4),
            new TemplateItem("TM19","Description",4),
            new TemplateItem("TM20","Description",4),
            new TemplateItem("TM21","Description",4),
            new TemplateItem("TM22","Description",4),
            new TemplateItem("TM23","Description",4),
            new TemplateItem("TM24","Description",4),
            new TemplateItem("TM25","Description",4),
            new TemplateItem("TM26","Description",4),
            new TemplateItem("TM27","Description",4),
            new TemplateItem("TM28","Description",4),
            new TemplateItem("TM29","Description",4),
            new TemplateItem("TM30","Description",4),
            new TemplateItem("TM31","Description",4),
            new TemplateItem("TM32","Description",4),
            new TemplateItem("TM33","Description",4),
            new TemplateItem("TM34","Description",4),
            new TemplateItem("TM35","Description",4),
            new TemplateItem("TM36","Description",4),
            new TemplateItem("TM37","Description",4),
            new TemplateItem("TM38","Description",4),
            new TemplateItem("TM39","Description",4),
            new TemplateItem("TM40","Description",4),
            new TemplateItem("TM41","Description",4),
            new TemplateItem("TM42","Description",4),
            new TemplateItem("TM43","Description",4),
            new TemplateItem("TM44","Description",4),
            new TemplateItem("TM45","Description",4),
            new TemplateItem("TM46","Description",4),
            new TemplateItem("TM47","Description",4),
            new TemplateItem("TM48","Description",4),
            new TemplateItem("TM49","Description",4),
            new TemplateItem("TM50","Description",4),
            new TemplateItem("TM51","Description",4),
            new TemplateItem("TM52","Description",4),
            new TemplateItem("TM53","Description",4),
            new TemplateItem("TM54","Description",4),
            new TemplateItem("TM55","Description",4),
            new TemplateItem("TM56","Description",4),
            new TemplateItem("TM57","Description",4),
            new TemplateItem("TM58","Description",4),
            new TemplateItem("TM59","Description",4),
            new TemplateItem("TM60","Description",4),
            new TemplateItem("TM61","Description",4),
            new TemplateItem("TM62","Description",4),
            new TemplateItem("TM63","Description",4),
            new TemplateItem("TM64","Description",4),
            new TemplateItem("TM65","Description",4),
            new TemplateItem("TM66","Description",4),
            new TemplateItem("TM67","Description",4),
            new TemplateItem("TM68","Description",4),
            new TemplateItem("TM69","Description",4),
            new TemplateItem("TM70","Description",4),
            new TemplateItem("TM71","Description",4),
            new TemplateItem("TM72","Description",4),
            new TemplateItem("TM73","Description",4),
            new TemplateItem("TM74","Description",4),
            new TemplateItem("TM75","Description",4),
            new TemplateItem("TM76","Description",4),
            new TemplateItem("TM77","Description",4),
            new TemplateItem("TM78","Description",4),
            new TemplateItem("TM79","Description",4),
            new TemplateItem("TM80","Description",4),
            new TemplateItem("TM81","Description",4),
            new TemplateItem("TM82","Description",4),
            new TemplateItem("TM83","Description",4),
            new TemplateItem("TM84","Description",4),
            new TemplateItem("TM85","Description",4),
            new TemplateItem("TM86","Description",4),
            new TemplateItem("TM87","Description",4),
            new TemplateItem("TM88","Description",4),
            new TemplateItem("TM89","Description",4),
            new TemplateItem("TM90","Description",4),
            new TemplateItem("TM91","Description",4),
            new TemplateItem("TM92","Description",4),
            new TemplateItem("HM01","Description",4),
            new TemplateItem("HM02","Description",4),
            new TemplateItem("HM03","Description",4),
            new TemplateItem("HM04","Description",4),
            new TemplateItem("HM05","Description",4),
            new TemplateItem("HM06","Description",4),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("Explorer Kit","Description",6),
            new TemplateItem("Loot Sack","Description",6),
            new TemplateItem("Rule Book","Description",6),
            new TemplateItem("Poké Radar","Description",6),
            new TemplateItem("Point Card","Description",6),
            new TemplateItem("Journal","Description",6),
            new TemplateItem("Seal Case","Description",6),
            new TemplateItem("Fashion Case","Description",6),
            new TemplateItem("Seal Bag","Description",6),
            new TemplateItem("Pal Pad","Description",6),
            new TemplateItem("Works Key","Description",6),
            new TemplateItem("Old Charm","Description",6),
            new TemplateItem("Galactic Key","Description",6),
            new TemplateItem("Red Chain","Description",6),
            new TemplateItem("Town Map","Description",6),
            new TemplateItem("Vs. Seeker","Description",6),
            new TemplateItem("Coin Case","Description",6),
            new TemplateItem("Old Rod","Description",6),
            new TemplateItem("Good Rod","Description",6),
            new TemplateItem("Super Rod","Description",6),
            new TemplateItem("Sprayduck","Description",6),
            new TemplateItem("Poffin Case","Description",6),
            new TemplateItem("Bike","Description",6),
            new TemplateItem("Suite Key","Description",6),
            new TemplateItem("Oak's Letter","Description",6),
            new TemplateItem("Lunar Wing","Description",6),
            new TemplateItem("Member Card","Description",6),
            new TemplateItem("Azure Flute","Description",6),
            new TemplateItem("S.S. Ticket","Description",6),
            new TemplateItem("Contest Pass","Description",6),
            new TemplateItem("Magma Stone","Description",6),
            new TemplateItem("Parcel","Description",6),
            new TemplateItem("Coupon 1","Description",6),
            new TemplateItem("Coupon 2","Description",6),
            new TemplateItem("Coupon 3","Description",6),
            new TemplateItem("Storage Key","Description",6),
            new TemplateItem("Secret Potion","Description",6),
            new TemplateItem("Vs. Recorder","Description",6),
            new TemplateItem("Gracidea","Description",6),
            new TemplateItem("Secret Key","Description",6),
            new TemplateItem("Apricorn Box","Description",6),
            new TemplateItem("Unown Report","Description",6),
            new TemplateItem("Berry Pots","Description",6),
            new TemplateItem("Dowsing Machine","Description",6),
            new TemplateItem("Blue Card","Description",6),
            new TemplateItem("Slowpoke Tail","Description",6),
            new TemplateItem("Clear Bell","Description",6),
            new TemplateItem("Card Key","Description",6),
            new TemplateItem("Basement Key","Description",6),
            new TemplateItem("Squirt Bottle","Description",6),
            new TemplateItem("Red Scale","Description",6),
            new TemplateItem("Lost Item","Description",6),
            new TemplateItem("Pass","Description",6),
            new TemplateItem("Machine Part","Description",6),
            new TemplateItem("Silver Wing","Description",6),
            new TemplateItem("Rainbow Wing","Description",6),
            new TemplateItem("Mystery Egg","Description",6),
            new TemplateItem("Red Apricorn","Description",1),
            new TemplateItem("Blue Apricorn","Description",1),
            new TemplateItem("Yellow Apricorn","Description",1),
            new TemplateItem("Green Apricorn","Description",1),
            new TemplateItem("Pink Apricorn","Description",1),
            new TemplateItem("White Apricorn","Description",1),
            new TemplateItem("Black Apricorn","Description",1),
            new TemplateItem("Fast Ball","Description",1),
            new TemplateItem("Level Ball","Description",1),
            new TemplateItem("Lure Ball","Description",1),
            new TemplateItem("Heavy Ball","Description",1),
            new TemplateItem("Love Ball","Description",1),
            new TemplateItem("Friend Ball","Description",1),
            new TemplateItem("Moon Ball","Description",1),
            new TemplateItem("Sport Ball","Description",1),
            new TemplateItem("Park Ball","Description",1),
            new TemplateItem("Photo Album","Description",6),
            new TemplateItem("GB Sounds","Description",6),
            new TemplateItem("Tidal Bell","Description",6),
            new TemplateItem("Rage Candy Bar","Description",2),
            new TemplateItem("Data Card 01","Description",1),
            new TemplateItem("Data Card 02","Description",1),
            new TemplateItem("Data Card 03","Description",1),
            new TemplateItem("Data Card 04","Description",1),
            new TemplateItem("Data Card 05","Description",1),
            new TemplateItem("Data Card 06","Description",1),
            new TemplateItem("Data Card 07","Description",1),
            new TemplateItem("Data Card 08","Description",1),
            new TemplateItem("Data Card 09","Description",1),
            new TemplateItem("Data Card 10","Description",1),
            new TemplateItem("Data Card 11","Description",1),
            new TemplateItem("Data Card 12","Description",1),
            new TemplateItem("Data Card 13","Description",1),
            new TemplateItem("Data Card 14","Description",1),
            new TemplateItem("Data Card 15","Description",1),
            new TemplateItem("Data Card 16","Description",1),
            new TemplateItem("Data Card 17","Description",1),
            new TemplateItem("Data Card 18","Description",1),
            new TemplateItem("Data Card 19","Description",1),
            new TemplateItem("Data Card 20","Description",1),
            new TemplateItem("Data Card 21","Description",1),
            new TemplateItem("Data Card 22","Description",1),
            new TemplateItem("Data Card 23","Description",1),
            new TemplateItem("Data Card 24","Description",1),
            new TemplateItem("Data Card 25","Description",1),
            new TemplateItem("Data Card 26","Description",1),
            new TemplateItem("Data Card 27","Description",1),
            new TemplateItem("Jade Orb","Description",6),
            new TemplateItem("Lock Capsule","Description",6),
            new TemplateItem("Red Orb","Description",1),
            new TemplateItem("Blue Orb","Description",1),
            new TemplateItem("Enigma Stone","Description",6),
            new TemplateItem("Prism Scale","Description",1),
            new TemplateItem("Eviolite","Description",1),
            new TemplateItem("Float Stone","Description",1),
            new TemplateItem("Rocky Helmet","Description",1),
            new TemplateItem("Air Balloon","Description",1),
            new TemplateItem("Red Card","Description",1),
            new TemplateItem("Ring Target","Description",1),
            new TemplateItem("Binding Band","Description",1),
            new TemplateItem("Absorb Bulb","Description",1),
            new TemplateItem("Cell Battery","Description",1),
            new TemplateItem("Eject Button","Description",1),
            new TemplateItem("Fire Gem","Description",1),
            new TemplateItem("Water Gem","Description",1),
            new TemplateItem("Electric Gem","Description",1),
            new TemplateItem("Grass Gem","Description",1),
            new TemplateItem("Ice Gem","Description",1),
            new TemplateItem("Fighting Gem","Description",1),
            new TemplateItem("Poison Gem","Description",1),
            new TemplateItem("Ground Gem","Description",1),
            new TemplateItem("Flying Gem","Description",1),
            new TemplateItem("Psychic Gem","Description",1),
            new TemplateItem("Bug Gem","Description",1),
            new TemplateItem("Rock Gem","Description",1),
            new TemplateItem("Ghost Gem","Description",1),
            new TemplateItem("Dragon Gem","Description",1),
            new TemplateItem("Dark Gem","Description",1),
            new TemplateItem("Steel Gem","Description",1),
            new TemplateItem("Normal Gem","Description",1),
            new TemplateItem("Health Wing","Description",2),
            new TemplateItem("Muscle Wing","Description",2),
            new TemplateItem("Resist Wing","Description",2),
            new TemplateItem("Genius Wing","Description",2),
            new TemplateItem("Clever Wing","Description",2),
            new TemplateItem("Swift Wing","Description",2),
            new TemplateItem("Pretty Wing","Description",1),
            new TemplateItem("Cover Fossil","Description",1),
            new TemplateItem("Plume Fossil","Description",1),
            new TemplateItem("Liberty Pass","Description",6),
            new TemplateItem("Pass Orb","Description",1),
            new TemplateItem("Dream Ball","Description",1),
            new TemplateItem("Poké Toy","Description",1),
            new TemplateItem("Prop Case","Description",6),
            new TemplateItem("Dragon Skull","Description",6),
            new TemplateItem("Balm Mushroom","Description",1),
            new TemplateItem("Big Nugget","Description",1),
            new TemplateItem("Pearl String","Description",1),
            new TemplateItem("Comet Shard","Description",1),
            new TemplateItem("Relic Copper","Description",1),
            new TemplateItem("Relic Silver","Description",1),
            new TemplateItem("Relic Gold","Description",1),
            new TemplateItem("Relic Vase","Description",1),
            new TemplateItem("Relic Band","Description",1),
            new TemplateItem("Relic Statue","Description",1),
            new TemplateItem("Relic Crown","Description",1),
            new TemplateItem("Casteliacone","Description",2),
            new TemplateItem("Dire Hit 2","Description",1),
            new TemplateItem("X Speed 2","Description",1),
            new TemplateItem("X Sp. Atk 2","Description",1),
            new TemplateItem("X Sp. Def 2","Description",1),
            new TemplateItem("X Defense 2","Description",1),
            new TemplateItem("X Attack 2","Description",1),
            new TemplateItem("X Accuracy 2","Description",1),
            new TemplateItem("X Speed 3","Description",1),
            new TemplateItem("X Sp. Atk 3","Description",1),
            new TemplateItem("X Sp. Def 3","Description",1),
            new TemplateItem("X Defense 3","Description",1),
            new TemplateItem("X Attack 3","Description",1),
            new TemplateItem("X Accuracy 3","Description",1),
            new TemplateItem("X Speed 6","Description",1),
            new TemplateItem("X Sp. Atk 6","Description",1),
            new TemplateItem("X Sp. Def 6","Description",1),
            new TemplateItem("X Defense 6","Description",1),
            new TemplateItem("X Attack 6","Description",1),
            new TemplateItem("X Accuracy 6","Description",1),
            new TemplateItem("Ability Urge","Description",1),
            new TemplateItem("Item Drop","Description",1),
            new TemplateItem("Item Urge","Description",1),
            new TemplateItem("Reset Urge","Description",1),
            new TemplateItem("Dire Hit 3","Description",1),
            new TemplateItem("Light Stone","Description",6),
            new TemplateItem("Dark Stone","Description",6),
            new TemplateItem("TM93","Description",4),
            new TemplateItem("TM94","Description",4),
            new TemplateItem("TM95","Description",4),
            new TemplateItem("Xtransceiver","Description",6),
            new TemplateItem("???","Description",6),
            new TemplateItem("Gram 1","Description",6),
            new TemplateItem("Gram 2","Description",6),
            new TemplateItem("Gram 3","Description",6),
            new TemplateItem("Xtransceiver","Description",6),
            new TemplateItem("Medal Box","Description",6),
            new TemplateItem("DNA Splicers","Description",6),
            new TemplateItem("DNA Splicers","Description",6),
            new TemplateItem("Permit","Description",6),
            new TemplateItem("Oval Charm","Description",6),
            new TemplateItem("Shiny Charm","Description",6),
            new TemplateItem("Plasma Card","Description",6),
            new TemplateItem("Grubby Hanky","Description",6),
            new TemplateItem("Colress Machine","Description",6),
            new TemplateItem("Dropped Item","Description",6),
            new TemplateItem("Dropped Item","Description",6),
            new TemplateItem("Reveal Glass","Description",6),
            new TemplateItem("Weakness Policy","Description",1),
            new TemplateItem("Assault Vest","Description",1),
            new TemplateItem("Holo Caster","Description",6),
            new TemplateItem("Prof's Letter","Description",6),
            new TemplateItem("Roller Skates","Description",6),
            new TemplateItem("Pixie Plate","Description",1),
            new TemplateItem("Ability Capsule","Description",2),
            new TemplateItem("Whipped Dream","Description",1),
            new TemplateItem("Sachet","Description",1),
            new TemplateItem("Luminous Moss","Description",1),
            new TemplateItem("Snowball","Description",1),
            new TemplateItem("Safety Goggles","Description",1),
            new TemplateItem("Poké Flute","Description",6),
            new TemplateItem("Rich Mulch","Description",1),
            new TemplateItem("Surprise Mulch","Description",1),
            new TemplateItem("Boost Mulch","Description",1),
            new TemplateItem("Amaze Mulch","Description",1),
            new TemplateItem("Gengarite","Description",1),
            new TemplateItem("Gardevoirite","Description",1),
            new TemplateItem("Ampharosite","Description",1),
            new TemplateItem("Venusaurite","Description",1),
            new TemplateItem("Charizardite X","Description",1),
            new TemplateItem("Blastoisinite","Description",1),
            new TemplateItem("Mewtwonite X","Description",1),
            new TemplateItem("Mewtwonite Y","Description",1),
            new TemplateItem("Blazikenite","Description",1),
            new TemplateItem("Medichamite","Description",1),
            new TemplateItem("Houndoominite","Description",1),
            new TemplateItem("Aggronite","Description",1),
            new TemplateItem("Banettite","Description",1),
            new TemplateItem("Tyranitarite","Description",1),
            new TemplateItem("Scizorite","Description",1),
            new TemplateItem("Pinsirite","Description",1),
            new TemplateItem("Aerodactylite","Description",1),
            new TemplateItem("Lucarionite","Description",1),
            new TemplateItem("Abomasite","Description",1),
            new TemplateItem("Kangaskhanite","Description",1),
            new TemplateItem("Gyaradosite","Description",1),
            new TemplateItem("Absolite","Description",1),
            new TemplateItem("Charizardite Y","Description",1),
            new TemplateItem("Alakazite","Description",1),
            new TemplateItem("Heracronite","Description",1),
            new TemplateItem("Mawilite","Description",1),
            new TemplateItem("Manectite","Description",1),
            new TemplateItem("Garchompite","Description",1),
            new TemplateItem("Latiasite","Description",1),
            new TemplateItem("Latiosite","Description",1),
            new TemplateItem("Roseli Berry","Description",3),
            new TemplateItem("Kee Berry","Description",3),
            new TemplateItem("Maranga Berry","Description",3),
            new TemplateItem("Sprinklotad","Description",6),
            new TemplateItem("TM96","Description",4),
            new TemplateItem("TM97","Description",4),
            new TemplateItem("TM98","Description",4),
            new TemplateItem("TM99","Description",4),
            new TemplateItem("TM100","Description",4),
            new TemplateItem("Power Plant Pass","Description",6),
            new TemplateItem("Mega Ring","Description",6),
            new TemplateItem("Intriguing Stone","Description",6),
            new TemplateItem("Common Stone","Description",6),
            new TemplateItem("Discount Coupon","Description",1),
            new TemplateItem("Elevator Key","Description",6),
            new TemplateItem("TMV Pass","Description",6),
            new TemplateItem("Honor of Kalos","Description",6),
            new TemplateItem("Adventure Rules","Description",6),
            new TemplateItem("Strange Souvenir","Description",1),
            new TemplateItem("Lens Case","Description",6),
            new TemplateItem("Makeup Bag","Description",6),
            new TemplateItem("Travel Trunk","Description",6),
            new TemplateItem("Lumiose Galette","Description",2),
            new TemplateItem("Shalour Sable","Description",2),
            new TemplateItem("Jaw Fossil","Description",1),
            new TemplateItem("Sail Fossil","Description",1),
            new TemplateItem("Looker Ticket","Description",6),
            new TemplateItem("Bicycle","Description",6),
            new TemplateItem("Holo Caster","Description",6),
            new TemplateItem("Fairy Gem","Description",1),
            new TemplateItem("Mega Charm","Description",6),
            new TemplateItem("Mega Glove","Description",6),
            new TemplateItem("Mach Bike","Description",6),
            new TemplateItem("Acro Bike","Description",6),
            new TemplateItem("Wailmer Pail","Description",6),
            new TemplateItem("Devon Parts","Description",6),
            new TemplateItem("Soot Sack","Description",6),
            new TemplateItem("Basement Key","Description",6),
            new TemplateItem("Pokéblock Kit","Description",6),
            new TemplateItem("Letter","Description",6),
            new TemplateItem("Eon Ticket","Description",6),
            new TemplateItem("Scanner","Description",6),
            new TemplateItem("Go-Goggles","Description",6),
            new TemplateItem("Meteorite","Description",6),
            new TemplateItem("Key to Room 1","Description",6),
            new TemplateItem("Key to Room 2","Description",6),
            new TemplateItem("Key to Room 4","Description",6),
            new TemplateItem("Key to Room 6","Description",6),
            new TemplateItem("Storage Key","Description",6),
            new TemplateItem("Devon Scope","Description",6),
            new TemplateItem("S.S. Ticket","Description",6),
            new TemplateItem("HM07","Description",4),
            new TemplateItem("Devon Scuba Gear","Description",6),
            new TemplateItem("Contest Costume","Description",6),
            new TemplateItem("Contest Costume","Description",6),
            new TemplateItem("Magma Suit","Description",6),
            new TemplateItem("Aqua Suit","Description",6),
            new TemplateItem("Pair of Tickets","Description",6),
            new TemplateItem("Mega Bracelet","Description",6),
            new TemplateItem("Mega Pendant","Description",6),
            new TemplateItem("Mega Glasses","Description",6),
            new TemplateItem("Mega Anchor","Description",6),
            new TemplateItem("Mega Stickpin","Description",6),
            new TemplateItem("Mega Tiara","Description",6),
            new TemplateItem("Mega Anklet","Description",6),
            new TemplateItem("Meteorite","Description",6),
            new TemplateItem("Swampertite","Description",5),
            new TemplateItem("Sceptilite","Description",5),
            new TemplateItem("Sablenite","Description",5),
            new TemplateItem("Altarianite","Description",5),
            new TemplateItem("Galladite","Description",5),
            new TemplateItem("Audinite","Description",5),
            new TemplateItem("Metagrossite","Description",5),
            new TemplateItem("Sharpedonite","Description",5),
            new TemplateItem("Slowbronite","Description",5),
            new TemplateItem("Steelixite","Description",5),
            new TemplateItem("Pidgeotite","Description",5),
            new TemplateItem("Glalitite","Description",5),
            new TemplateItem("Diancite","Description",5),
            new TemplateItem("Prison Bottle","Description",6),
            new TemplateItem("Mega Cuff","Description",6),
            new TemplateItem("Cameruptite","Description",5),
            new TemplateItem("Lopunnite","Description",5),
            new TemplateItem("Salamencite","Description",5),
            new TemplateItem("Beedrillite","Description",5),
            new TemplateItem("Meteorite","Description",6),
            new TemplateItem("Meteorite","Description",6),
            new TemplateItem("Key Stone","Description",6),
            new TemplateItem("Meteorite Shard","Description",6),
            new TemplateItem("Eon Flute","Description",6),
            new TemplateItem("Normalium Z","Description",5),
            new TemplateItem("Firium Z","Description",5),
            new TemplateItem("Waterium Z","Description",5),
            new TemplateItem("Electrium Z","Description",5),
            new TemplateItem("Grassium Z","Description",5),
            new TemplateItem("Icium Z","Description",5),
            new TemplateItem("Fightinium Z","Description",5),
            new TemplateItem("Poisonium Z","Description",5),
            new TemplateItem("Groundium Z","Description",5),
            new TemplateItem("Flyinium Z","Description",5),
            new TemplateItem("Psychium Z","Description",5),
            new TemplateItem("Buginium Z","Description",5),
            new TemplateItem("Rockium Z","Description",5),
            new TemplateItem("Ghostium Z","Description",5),
            new TemplateItem("Dragonium Z","Description",5),
            new TemplateItem("Darkinium Z","Description",5),
            new TemplateItem("Steelium Z","Description",5),
            new TemplateItem("Fairium Z","Description",5),
            new TemplateItem("Pikanium Z","Description",5),
            new TemplateItem("Bottle Cap","Description",1),
            new TemplateItem("Gold Bottle Cap","Description",1),
            new TemplateItem("Z-Ring","Description",6),
            new TemplateItem("Decidium Z","Description",5),
            new TemplateItem("Incinium Z","Description",5),
            new TemplateItem("Primarium Z","Description",5),
            new TemplateItem("Tapunium Z","Description",5),
            new TemplateItem("Marshadium Z","Description",5),
            new TemplateItem("Aloraichium Z","Description",5),
            new TemplateItem("Snorlium Z","Description",5),
            new TemplateItem("Eevium Z","Description",5),
            new TemplateItem("Mewnium Z","Description",5),
            new TemplateItem("Normalium Z","Description",5),
            new TemplateItem("Firium Z","Description",5),
            new TemplateItem("Waterium Z","Description",5),
            new TemplateItem("Electrium Z","Description",5),
            new TemplateItem("Grassium Z","Description",5),
            new TemplateItem("Icium Z","Description",5),
            new TemplateItem("Fightinium Z","Description",5),
            new TemplateItem("Poisonium Z","Description",5),
            new TemplateItem("Groundium Z","Description",5),
            new TemplateItem("Flyinium Z","Description",5),
            new TemplateItem("Psychium Z","Description",5),
            new TemplateItem("Buginium Z","Description",5),
            new TemplateItem("Rockium Z","Description",5),
            new TemplateItem("Ghostium Z","Description",5),
            new TemplateItem("Dragonium Z","Description",5),
            new TemplateItem("Darkinium Z","Description",5),
            new TemplateItem("Steelium Z","Description",5),
            new TemplateItem("Fairium Z","Description",5),
            new TemplateItem("Pikanium Z","Description",5),
            new TemplateItem("Decidium Z","Description",5),
            new TemplateItem("Incinium Z","Description",5),
            new TemplateItem("Primarium Z","Description",5),
            new TemplateItem("Tapunium Z","Description",5),
            new TemplateItem("Marshadium Z","Description",5),
            new TemplateItem("Aloraichium Z","Description",5),
            new TemplateItem("Snorlium Z","Description",5),
            new TemplateItem("Eevium Z","Description",5),
            new TemplateItem("Mewnium Z","Description",5),
            new TemplateItem("Pikashunium Z","Description",5),
            new TemplateItem("Pikashunium Z","Description",5),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("Forage Bag","Description",6),
            new TemplateItem("Fishing Rod","Description",6),
            new TemplateItem("Professor's Mask","Description",6),
            new TemplateItem("Festival Ticket","Description",1),
            new TemplateItem("Sparkling Stone","Description",6),
            new TemplateItem("Adrenaline Orb","Description",1),
            new TemplateItem("Zygarde Cube","Description",6),
            new TemplateItem("???","Description",0),
            new TemplateItem("Ice Stone","Description",1),
            new TemplateItem("Ride Pager","Description",6),
            new TemplateItem("Beast Ball","Description",1),
            new TemplateItem("Big Malasada","Description",2),
            new TemplateItem("Red Nectar","Description",1),
            new TemplateItem("Yellow Nectar","Description",1),
            new TemplateItem("Pink Nectar","Description",1),
            new TemplateItem("Purple Nectar","Description",1),
            new TemplateItem("Sun Flute","Description",6),
            new TemplateItem("Moon Flute","Description",6),
            new TemplateItem("???","Description",0),
            new TemplateItem("Enigmatic Card","Description",6),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("Terrain Extender","Description",1),
            new TemplateItem("Protective Pads","Description",1),
            new TemplateItem("Electric Seed","Description",1),
            new TemplateItem("Psychic Seed","Description",1),
            new TemplateItem("Misty Seed","Description",1),
            new TemplateItem("Grassy Seed","Description",1),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("???","Description",0),
            new TemplateItem("Fighting Memory","Description",1),
            new TemplateItem("Flying Memory","Description",1),
            new TemplateItem("Poison Memory","Description",1),
            new TemplateItem("Ground Memory","Description",1),
            new TemplateItem("Rock Memory","Description",1),
            new TemplateItem("Bug Memory","Description",1),
            new TemplateItem("Ghost Memory","Description",1),
            new TemplateItem("Steel Memory","Description",1),
            new TemplateItem("Fire Memory","Description",1),
            new TemplateItem("Water Memory","Description",1),
            new TemplateItem("Grass Memory","Description",1),
            new TemplateItem("Electric Memory","Description",1),
            new TemplateItem("Psychic Memory","Description",1),
            new TemplateItem("Ice Memory","Description",1),
            new TemplateItem("Dragon Memory","Description",1),
            new TemplateItem("Dark Memory","Description",1),
            new TemplateItem("Fairy Memory","Description",1),
            new TemplateItem("Solganium Z","Description",5),
            new TemplateItem("Lunalium Z","Description",5),
            new TemplateItem("Ultranecrozium Z","Description",5),
            new TemplateItem("Mimikium Z","Description",5),
            new TemplateItem("Lycanium Z","Description",5),
            new TemplateItem("Kommonium Z","Description",5),
            new TemplateItem("Solganium Z","Description",5),
            new TemplateItem("Lunalium Z","Description",5),
            new TemplateItem("Ultranecrozium Z","Description",5),
            new TemplateItem("Mimikium Z","Description",5),
            new TemplateItem("Lycanium Z","Description",5),
            new TemplateItem("Kommonium Z","Description",5),
            new TemplateItem("Z-Power Ring","Description",6),
            new TemplateItem("Pink Petal","Description",6),
            new TemplateItem("Orange Petal","Description",6),
            new TemplateItem("Blue Petal","Description",6),
            new TemplateItem("Red Petal","Description",6),
            new TemplateItem("Green Petal","Description",6),
            new TemplateItem("Yellow Petal","Description",6),
            new TemplateItem("Purple Petal","Description",6),
            new TemplateItem("Rainbow Flower","Description",6),
            new TemplateItem("Surge Badge","Description",6),
            new TemplateItem("N-Solarizer","Description",6),
            new TemplateItem("N-Lunarizer","Description",6),
            new TemplateItem("N-Solarizer","Description",6),
            new TemplateItem("N-Lunarizer","Description",6),
            new TemplateItem("Tart Apple","Description",1),
            new TemplateItem("Sweet Apple","Description",1)
    };

}
